apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 210-azure-portworx-storage
  labels:
    type: software
    code: '210'
    platform: azure
    storage: portworx
  annotations:
    displayName: Azure - Portworx Cluster Storage
    description: Installs Portworx into an OCP cluster on Azure
spec:
  modules:
    - name: azure-portworx
      alias: azure-portworx
      version: v1.0.2
      variables:
        - name: region
          scope: global
        - name: name_prefix
          scope: global
        - name: client_id
          scope: global
        - name: client_secret
          scope: global
        - name: subscription_id
          scope: global
        - name: tenant_id
          scope: global
        - name: portworx_spec_file
          scope: global
          important: true
        - name: portworx_spec
          scope: global
    - name: ocp-login
      alias: cluster
      version: v1.6.0
  variables:
    - name: azure_subscription_id
      type: string
      description: >-
        The subscription id of the Azure account where the OpenShift cluster has
        been provisioned
    - name: azure_tenant_id
      type: string
      description: >-
        The tenant id of the Azure account where the OpenShift cluster has been
        provisioned
    - name: azure_client_id
      type: string
      description: The client id used to access the Azure account
    - name: azure_client_secret
      type: string
      description: The client secret used to access the Azure account
    - name: portworx_spec_file
      type: string
      description: >-
        The path to the file that contains the yaml spec for the Portworx
        config. Either the `portworx_spec_file` or `portworx_spec` must be
        provided. The instructions for creating this configuration can be found
        at
        https://github.com/cloud-native-toolkit/terraform-azure-portworx/blob/main/PORTWORX_CONFIG.md
      defaultValue: ''
    - name: portworx_spec
      type: string
      description: >-
        The yaml spec for the Portworx config. Either the `portworx_spec_file`
        or `portworx_spec` must be provided. The instructions for creating this
        configuration can be found at
        https://github.com/cloud-native-toolkit/terraform-azure-portworx/blob/main/PORTWORX_CONFIG.md
      defaultValue: ''
    - name: azure-portworx_enable_encryption
      type: bool
      description: Flag indicating portworx volumes should be encrypted
      defaultValue: false
    - name: server_url
      type: string
      description: The url for the OpenShift api
    - name: cluster_login_token
      type: string
      description: Token used for authentication
      sensitive: true
