apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 405-mas-manage
  labels:
    type: software
    code: '405'
  annotations:
    displayName: Maximo Application Suite - Manage Application
    description: GitOps deployment of Maximo Manage application for OpenShift
    deployment-type/gitops: 'true'
    dependencies.cloudnativetoolkit.dev/needs: gitops,storage
    dependencies.cloudnativetoolkit.dev/needs_gitops: gitops_repo
    dependencies.cloudnativetoolkit.dev/needs_storage: util-storage-class-manager
spec:
  version: v2.0.0
  modules:
    - name: gitops-mas-manage
      alias: gitops-mas-manage
      version: v2.1.1
    - name: gitops-repo
      alias: gitops_repo
      version: v1.23.3
    - name: util-mas-core-existing
      alias: mas_core_existing
      version: v1.0.0
    - name: util-storage-class-manager
      alias: util-storage-class-manager
      version: v1.0.3
      variables:
        - name: rwx_storage_class
          scope: global
        - name: rwo_storage_class
          scope: global
        - name: file_storage_class
          scope: global
        - name: block_storage_class
          scope: global
    - name: util-clis
      version: v1.19.0
  variables:
    - name: gitops_repo_host
      type: string
      description: >-
        The host for the git repository. The git host used can be a GitHub,
        GitHub Enterprise, Gitlab, Bitbucket, Gitea or Azure DevOps server. If
        the host is null assumes in-cluster Gitea instance will be used.
      value: ''
    - name: gitops_repo_org
      type: string
      description: >-
        The org/group where the git repository exists/will be provisioned. If
        the value is left blank then the username org will be used.
      value: ''
    - name: gitops_repo_project
      type: string
      description: >-
        The project that will be used for the git repo. (Primarily used for
        Azure DevOps repos)
      value: ''
    - name: gitops_repo_username
      type: string
      description: The username of the user with access to the repository
      value: ''
    - name: gitops_repo_token
      type: string
      description: The personal access token used to access the repository
      value: ''
      sensitive: true
    - name: gitops_repo_repo
      type: string
      description: >-
        The short name of the repository (i.e. the part after the org/group
        name)
    - name: mas_core_existing_core_namespace
      type: string
      description: The namespace where the module will be deployed
    - name: mas_core_existing_entitlement_secret_name
      type: string
      description: The name of the secret that contains the entitlement_key
    - name: mas_core_existing_mas_instance_id
      type: string
      description: The identifier of the MAS instance that was created
    - name: mas_core_existing_mas_workspace_id
      type: string
      description: The identifier of the MAS workspace that was created
    - name: rwx_storage_class
      type: string
      description: The storage class to use for Read-Write-Many volumes
    - name: rwo_storage_class
      type: string
      description: The storage class to use for Read-Write-One volumes
    - name: file_storage_class
      type: string
      description: The storage class to use for File storage volumes
    - name: block_storage_class
      type: string
      description: The storage class to use for Block storage volumes
