apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 200-openshift-gitops
  labels:
    type: software
    code: '200'
  annotations:
    displayName: OpenShift GitOps Bootstrap
    description: >-
      Provisions OpenShift GitOps (ArgoCD) into an existing cluster and
      bootstraps it to a gitops repository
    vpn/required: 'true'
    dependencies.cloudnativetoolkit.dev/provides: gitops
    dependencies.cloudnativetoolkit.dev/needs: cluster
    dependencies.cloudnativetoolkit.dev/provides_gitops: gitops_repo
    dependencies.cloudnativetoolkit.dev/needs_cluster: cluster
spec:
  modules:
    - name: namespace
      alias: gitea_namespace
      version: v3.2.4
      variables:
        - name: name
          value: gitea
    - name: gitea
      alias: gitea
      version: v0.5.1
      dependencies:
        - id: namespace
          ref: gitea_namespace
    - name: gitops-cluster-config
      alias: config
      version: v1.1.1
    - name: gitops-console-link-job
      alias: gitops-console-link-job
      version: v1.5.1
    - name: gitops-namespace
      alias: toolkit_namespace
      version: v1.12.2
      default: true
      variables:
        - name: name
          value: toolkit
    - name: gitops-repo
      alias: gitops_repo
      version: v1.23.3
    - name: argocd-bootstrap
      alias: argocd-bootstrap
      version: v1.13.1
      variables:
        - name: create_webhook
          value: true
    - name: ocp-login
      alias: cluster
      version: v1.6.2
    - name: olm
      version: v1.3.5
    - name: util-clis
      version: v1.19.0
    - name: sealed-secret-cert
      version: v1.0.1
  variables:
    - name: config_banner_text
      type: string
      description: The text that will appear in the top banner in the cluster
    - name: gitops_repo_host
      type: string
      description: >-
        The host for the git repository. The git host used can be a GitHub,
        GitHub Enterprise, Gitlab, Bitbucket, Gitea or Azure DevOps server. If
        the host is null assumes in-cluster Gitea instance will be used.
      value: ''
    - name: gitops_repo_org
      type: string
      description: >-
        The org/group where the git repository exists/will be provisioned. If
        the value is left blank then the username org will be used.
      value: ''
    - name: gitops_repo_project
      type: string
      description: >-
        The project that will be used for the git repo. (Primarily used for
        Azure DevOps repos)
      value: ''
    - name: gitops_repo_username
      type: string
      description: The username of the user with access to the repository
      value: ''
    - name: gitops_repo_token
      type: string
      description: The personal access token used to access the repository
      value: ''
      sensitive: true
    - name: gitops_repo_repo
      type: string
      description: >-
        The short name of the repository (i.e. the part after the org/group
        name)
    - name: server_url
      type: string
      description: The url for the OpenShift api
    - name: cluster_login_token
      type: string
      description: Token used for authentication
      sensitive: true
