apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 200-openshift-gitops
  labels:
    type: software
    code: '200'
  annotations:
    displayName: OpenShift GitOps Bootstrap
    description: >-
      Provisions OpenShift GitOps (ArgoCD) into an existing cluster and
      bootstraps it to a gitops repository
spec:
  modules:
    - name: gitea
      alias: gitea
      version: v0.4.1
      dependencies:
        - id: namespace
          ref: gitea_namespace
    - name: gitops-cluster-config
      alias: gitops-cluster-config
      version: v1.0.0
    - name: gitops-console-link-job
      alias: gitops-console-link-job
      version: v1.4.6
    - name: gitops-namespace
      alias: gitea_namespace
      version: v1.11.2
      variables: &ref_0
        - name: name
          value: gitea
    - name: gitops-namespace
      alias: toolkit_namespace
      version: v1.11.2
      default: true
      variables:
        - name: name
          value: toolkit
    - name: gitops-repo
      alias: gitops_repo
      version: v1.20.5
    - name: argocd-bootstrap
      alias: argocd-bootstrap
      version: v1.12.0
      variables:
        - name: create_webhook
          value: true
        - name: prefix
          value: maximo
    - name: ocp-login
      alias: cluster
      version: v1.4.2
    - name: olm
      version: v1.3.2
    - name: gitops-namespace
      alias: gitea_namespace
      version: v3.2.3
      variables: *ref_0
    - name: sealed-secret-cert
      version: v1.0.1
  variables:
    - name: gitops-cluster-config_banner_text
      type: string
      description: The text that will appear in the top banner in the cluster
    - name: gitops_repo_host
      type: string
      description: >-
        The host for the git repository. The git host used can be a GitHub,
        GitHub Enterprise, Gitlab, Bitbucket, Gitea or Azure DevOps server. If
        the host is null assumes in-cluster Gitea instance will be used.
      defaultValue: ''
    - name: gitops_repo_org
      type: string
      description: >-
        The org/group where the git repository exists/will be provisioned. If
        the value is left blank then the username org will be used.
      defaultValue: ''
    - name: gitops_repo_project
      type: string
      description: >-
        The project that will be used for the git repo. (Primarily used for
        Azure DevOps repos)
      defaultValue: ''
    - name: gitops_repo_username
      type: string
      description: The username of the user with access to the repository
      defaultValue: ''
    - name: gitops_repo_token
      type: string
      description: The personal access token used to access the repository
      defaultValue: ''
      sensitive: true
    - name: gitops_repo_repo
      type: string
      description: >-
        The short name of the repository (i.e. the part after the org/group
        name)
    - name: server_url
      type: string
      description: The url for the OpenShift api
    - name: cluster_login_token
      type: string
      description: Token used for authentication
      sensitive: true
