apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 210-aws-portworx-storage
  labels:
    type: infrastructure
    code: '210'
    platform: aws
    storage: portworx
  annotations:
    displayName: AWS - Portworx Cluster Storage
    description: Installs Portworx in and OCP cluster on AWS
spec:
  modules:
    - name: aws-portworx
      alias: aws-portworx
      version: v0.1.0
    - name: ocp-login
      alias: cluster
      version: v1.6.0
  variables:
    - name: region
      type: string
      description: AWS Region the cluster is deployed in
    - name: aws-portworx_portworx_spec
      type: string
      defaultValue: ''
    - name: aws-portworx_portworx_spec_file
      type: string
      description: >-
        The path to the file that contains the yaml spec for the Portworx
        config. Either the `portworx_spec_file` or `portworx_spec` must be
        provided. The instructions for creating this configuration can be found
        at
        https://github.com/cloud-native-toolkit/terraform-azure-portworx/blob/main/PORTWORX_CONFIG.md
      defaultValue: ''
    - name: aws-portworx_enable_encryption
      type: bool
      description: Flag indicating portworx volumes should be encrypted
      defaultValue: false
    - name: server_url
      type: string
      description: The url for the OpenShift api
    - name: cluster_login_token
      type: string
      description: Token used for authentication
      sensitive: true
