apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 210-ibm-portworx-storage
  labels:
    type: infrastructure
    platform: ibm
    code: '210'
    storage: portworx
  annotations:
    displayName: IBM - Portworx Cluster Storage
    description: Installs Portworx in an IBM cluster
spec:
  modules:
    - name: gitops-ibm-portworx
      alias: gitops-ibm-portworx
      version: v0.2.2
    - name: gitops-namespace
      alias: portworx_namespace
      version: v1.11.2
      default: true
      variables:
        - name: name
          value: portworx
    - name: ibm-resource-group
      alias: resource_group
      version: v3.2.15
    - name: gitops-repo
      alias: gitops_repo
      version: v1.18.1
    - name: gitops-ibmcloud-operator
      version: v0.2.1
  variables:
    - name: ibmcloud_api_key
      type: string
      description: The api key for the IBM Cloud account
      sensitive: true
    - name: resource_group_name
      type: string
      description: The name of the resource group
    - name: gitops_repo_host
      type: string
      description: The host for the git repository.
      defaultValue: ''
    - name: gitops_repo_org
      type: string
      description: The org/group where the git repository exists/will be provisioned.
      defaultValue: ''
    - name: gitops_repo_username
      type: string
      description: The username of the user with access to the repository
      defaultValue: ''
    - name: gitops_repo_token
      type: string
      description: The personal access token used to access the repository
      defaultValue: ''
      sensitive: true
    - name: gitops_repo_repo
      type: string
      description: >-
        The short name of the repository (i.e. the part after the org/group
        name)
