apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 105-mock
  labels:
    type: infrastructure
    code: '105'
  annotations:
    displayName: VPC OpenShift mock
    description: Mock layer for VPC OpenShift
    path: .mocks
spec:
  modules:
    - name: ocp-login
      alias: cluster
      version: v1.4.2
  variables:
    - name: server_url
      type: string
      description: The url for the OpenShift api
    - name: cluster_login_token
      type: string
      description: Token used for authentication
      sensitive: true
