name: Verify

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verify:
    uses: ./.github/workflows/verify-workflow.yaml
    secrets:
      IBMCLOUD_API_KEY: ${{ secrets.IBMCLOUD_API_KEY }}
      ENTITLEMENT_KEY: ${{ secrets.ENTITLEMENT_KEY }}
